export const dynamic = 'force-dynamic';

import { ChevronDown } from 'lucide-react';
import { PageHeader } from '@/components/PageHeader';
import { ResponsiveFormSection } from '@/components/ResponsiveFormSection';
import { getCurrentAdminProfile } from '@/lib/current';
import { createAdminSupabase } from '@/lib/supabase/admin';
import { ServerTablePagination } from '@/components/ServerTablePagination';
import { parseServerPagination } from '@/lib/pagination';

function statusLabel(value?:string){const labels:Record<string,string>={ativo:'Ativo',inativo:'Inativo',suspenso:'Suspenso'};return labels[String(value||'')]||value||'-'}

export default async function Usuarios({searchParams}:{searchParams?:Promise<Record<string,string|string[]|undefined>>}){
  const {profile}=await getCurrentAdminProfile();const admin=createAdminSupabase();const query=await searchParams;const {page,pageSize,from,to}=parseServerPagination(query);const {data,count}=await admin.from('profiles').select('*',{count:'exact'}).eq('law_firm_id',profile.law_firm_id).order('created_at',{ascending:false}).range(from,to);const users=data||[];const totalRows=count||0;
  const form=<form action="/api/users" method="post" className="compact-form-grid grid gap-2.5 md:grid-cols-3"><input className="input compact-input" name="full_name" placeholder="Nome completo" required/><input className="input compact-input" name="email" type="email" placeholder="E-mail" required/><input className="input compact-input" name="phone" placeholder="Celular"/><input className="input compact-input" name="oab_number" placeholder="OAB (opcional)"/><div><input className="input compact-input" name="password" type="password" autoComplete="new-password" placeholder="Senha provisória forte" required/><p className="mt-1 text-[9px] font-bold text-slate-500">Mín. 14 caracteres, maiúscula, minúscula, número e símbolo.</p></div><button className="btn btn-primary">Criar usuário</button></form>;
  return <div><PageHeader title="Usuários" subtitle="Pessoas autorizadas a acessar o AdvOS."/><ResponsiveFormSection title="Novo usuário" description="Cadastro de acesso interno.">{form}</ResponsiveFormSection>
    <div className="hidden md:block table-responsive"><table className="table professional-table min-w-[760px]"><thead><tr><th>Nome</th><th>E-mail</th><th>Celular</th><th>OAB</th><th>Status</th><th>Acesso</th></tr></thead><tbody>{users.map((u:any)=><tr key={u.id}><td><b>{u.full_name||'-'}</b></td><td><span className="table-ellipsis max-w-[240px]">{u.email||'-'}</span></td><td>{u.phone||'-'}</td><td>{u.oab_number||'-'}</td><td><span className={`badge ${u.status==='ativo'?'badge-ok':'badge-warn'}`}>{statusLabel(u.status)}</span></td><td>{String(u.auth_user_id||'')===String(profile.auth_user_id||'')?<span className="text-[10px] font-bold text-slate-400">Sua conta</span>:<form action="/api/users" method="post"><input type="hidden" name="action" value="toggle_status"/><input type="hidden" name="profile_id" value={u.id}/><input type="hidden" name="status" value={u.status==='ativo'?'inativo':'ativo'}/><button className="compact-action-button" type="submit">{u.status==='ativo'?'Desativar':'Ativar'}</button></form>}</td></tr>)}</tbody></table></div>
    <div className="mobile-record-list md:hidden">{users.map((u:any)=><details className="mobile-record" key={u.id}><summary><div className="mobile-record-main"><strong>{u.full_name||'-'}</strong><span>{u.email||'-'}</span></div><div className="mobile-record-side"><span className={`mobile-status-dot ${u.status==='ativo'?'is-paid':'is-waiting'}`}>{statusLabel(u.status)}</span><ChevronDown size={15} className="disclosure-chevron"/></div></summary><div className="mobile-record-details"><div className="mobile-detail-grid"><div><span>Celular</span><b>{u.phone||'-'}</b></div><div><span>OAB</span><b>{u.oab_number||'-'}</b></div></div>{String(u.auth_user_id||'')!==String(profile.auth_user_id||'')&&<form action="/api/users" method="post" className="mt-3"><input type="hidden" name="action" value="toggle_status"/><input type="hidden" name="profile_id" value={u.id}/><input type="hidden" name="status" value={u.status==='ativo'?'inativo':'ativo'}/><button className="btn btn-secondary w-full" type="submit">{u.status==='ativo'?'Desativar acesso':'Ativar acesso'}</button></form>}</div></details>)}</div>
    <ServerTablePagination basePath="/app/usuarios" page={page} pageSize={pageSize} totalItems={totalRows}/>{!users.length&&<p className="empty-state">Nenhum usuário cadastrado.</p>}</div>;
}
