'use client';
import {useState} from 'react';
import {CheckCircle2, Eye, Loader2} from 'lucide-react';
export default function OfficeSignClient({requestId,documentId,title}:{requestId:string,documentId:string,title:string}){
 const [viewed,setViewed]=useState(false); const [iframeLoaded,setIframeLoaded]=useState(false); const [busy,setBusy]=useState(false); const [message,setMessage]=useState(''); const [done,setDone]=useState(false);
 const markViewed=async()=>{setBusy(true);setMessage('');try{const r=await fetch('/api/signatures/office-viewed',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({requestId})});const j=await r.json();if(!r.ok||!j.ok)throw new Error(j.error||'Não foi possível registrar a visualização.');setViewed(true)}catch(e:any){setMessage(e.message)}finally{setBusy(false)}};
 const sign=async()=>{if(!viewed){setMessage('Visualize o documento e confirme a leitura antes de assinar.');return}setBusy(true);setMessage('');try{const r=await fetch('/api/signatures/sign-office',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({requestId})});const j=await r.json();if(!r.ok||!j.ok)throw new Error(j.error||'Não foi possível assinar.');setDone(true)}catch(e:any){setMessage(e.message)}finally{setBusy(false)}};
 if(done)return <main className="min-h-screen bg-slate-50 p-6"><div className="mx-auto max-w-xl card p-8 text-center"><CheckCircle2 className="mx-auto text-emerald-600" size={52}/><h1 className="mt-4 text-2xl font-black">Documento assinado</h1><p className="mt-2 text-sm text-slate-600">Daniel Costa Ladeira concluiu a assinatura eletrônica.</p></div></main>;
 return <main className="min-h-screen bg-slate-50 p-4 md:p-8"><div className="mx-auto max-w-5xl grid gap-4 lg:grid-cols-[1fr_360px]"><section className="card overflow-hidden"><div className="border-b p-4"><h1 className="text-lg font-black">{title}</h1><p className="text-xs font-semibold text-slate-500">Assinatura do escritório — Daniel Costa Ladeira</p></div><div className="aspect-[1/1.3] bg-slate-100"><iframe title="Documento" src={`/api/documents/file/${documentId}`} onLoad={()=>setIframeLoaded(true)} className="h-full w-full border-0"/></div></section><aside className="card p-5"><div className="rounded-2xl border p-4"><div className="flex items-center gap-2 font-black"><Eye size={17}/> Visualização obrigatória</div><p className="mt-2 text-xs leading-5 text-slate-600">Visualize o documento acima antes de assinar.</p><label className="mt-3 flex items-start gap-2 rounded-xl border p-3 text-xs font-semibold"><input type="checkbox" checked={viewed} onChange={e=>setViewed(e.target.checked)} className="mt-0.5"/>Li e visualizei o documento completo.</label><button className="btn btn-secondary mt-3 w-full" disabled={!iframeLoaded||busy||!viewed} onClick={markViewed}>Confirmar visualização</button></div>{message&&<div className="mt-4 rounded-xl bg-amber-50 p-3 text-xs font-semibold text-amber-800">{message}</div>}<div className="mt-4 rounded-2xl bg-slate-50 p-4 text-xs leading-5 text-slate-600">Não é necessário token, OTP, selfie ou assinatura desenhada. Daniel assina como usuário autenticado do AdvOS.</div><button className="btn btn-primary mt-4 w-full" disabled={busy||!viewed} onClick={sign}>{busy?<Loader2 className="animate-spin"/>:<CheckCircle2 size={16}/>}Assinar documento</button></aside></div></main>
}
