export const dynamic = 'force-dynamic';

import { ChevronDown } from 'lucide-react';
import { PageHeader } from '@/components/PageHeader';
import { ResponsiveFormSection } from '@/components/ResponsiveFormSection';
import { getCurrentProfile } from '@/lib/current';
import { createAdminSupabase } from '@/lib/supabase/admin';
import { ServerTablePagination } from '@/components/ServerTablePagination';
import { parseServerPagination } from '@/lib/pagination';
import { money } from '@/lib/utils';

function statusLabel(value?: string) { const labels: Record<string,string> = { ativo:'Ativo', suspenso:'Suspenso', arquivado:'Arquivado', encerrado:'Encerrado' }; return labels[String(value || '')] || value || '-'; }

export default async function Processos({ searchParams }: { searchParams?: Promise<Record<string,string|string[]|undefined>> }) {
  const {profile}=await getCurrentProfile(); const admin=createAdminSupabase(); const query=await searchParams; const {page,pageSize,from,to}=parseServerPagination(query);
  const [cases,clients]=await Promise.all([admin.from('cases').select('*, clients(name)',{count:'exact'}).eq('law_firm_id',profile.law_firm_id).order('created_at',{ascending:false}).range(from,to),admin.from('clients').select('id,name').eq('law_firm_id',profile.law_firm_id)]);
  const rows=cases.data||[]; const totalRows=cases.count||0;
  const form=<form action="/api/cases" method="post" className="compact-form-grid grid gap-2.5 md:grid-cols-4">
    <select className="input compact-input" name="client_id"><option value="">Cliente</option>{(clients.data||[]).map((c:any)=><option value={c.id} key={c.id}>{c.name}</option>)}</select><input className="input compact-input" name="case_number" placeholder="Nº do processo"/><select className="input compact-input" name="area" defaultValue="cível"><option value="cível">Cível</option><option value="trabalhista">Trabalhista</option><option value="família">Família</option><option value="previdenciário">Previdenciário</option><option value="consumidor">Consumidor</option><option value="criminal">Criminal</option><option value="empresarial">Empresarial</option><option value="tributário">Tributário</option><option value="imobiliário">Imobiliário</option></select><input className="input compact-input" name="action_type" placeholder="Tipo de ação"/>
    <input className="input compact-input" name="court" placeholder="Tribunal ou vara"/><input className="input compact-input" name="district" placeholder="Comarca"/><input className="input compact-input" name="opposing_party" placeholder="Parte contrária"/><input className="input compact-input" name="responsible" placeholder="Responsável"/><input className="input compact-input" name="phase" placeholder="Fase atual"/><select className="input compact-input" name="status" defaultValue="ativo"><option value="ativo">Ativo</option><option value="suspenso">Suspenso</option><option value="arquivado">Arquivado</option><option value="encerrado">Encerrado</option></select><input className="input compact-input" name="claim_value" placeholder="Valor da causa" type="number" step="0.01"/><input className="input compact-input" name="notes" placeholder="Observações"/><button className="btn btn-primary md:col-span-4">Cadastrar processo</button>
  </form>;
  return <div><PageHeader title="Processos" subtitle="Processos, fases, áreas e responsáveis sem excesso de informação na tela."/><ResponsiveFormSection title="Novo processo" description="O formulário completo fica recolhido no PWA.">{form}</ResponsiveFormSection>
    <div className="hidden md:block table-responsive"><table className="table professional-table min-w-[800px]"><thead><tr><th>Processo</th><th>Cliente</th><th>Ação</th><th>Área</th><th>Fase</th><th>Status</th><th>Valor</th></tr></thead><tbody>{rows.map((c:any)=><tr key={c.id}><td><b>{c.case_number||'Sem número'}</b></td><td><span className="table-ellipsis max-w-[190px]">{c.clients?.name||'-'}</span></td><td><span className="table-ellipsis max-w-[210px]">{c.action_type||'-'}</span></td><td>{c.area||'-'}</td><td><span className="table-ellipsis max-w-[160px]">{c.phase||'-'}</span></td><td><span className="badge badge-info">{statusLabel(c.status)}</span></td><td>{money(c.claim_value)}</td></tr>)}</tbody></table></div>
    <div className="mobile-record-list md:hidden">{rows.map((c:any)=><details className="mobile-record" key={c.id}><summary><div className="mobile-record-main"><strong>{c.case_number||'Sem número'}</strong><span>{c.clients?.name||'Sem cliente'} · {c.area||'Sem área'}</span></div><div className="mobile-record-side"><span className="mobile-status-dot">{statusLabel(c.status)}</span><ChevronDown size={15} className="disclosure-chevron"/></div></summary><div className="mobile-record-details"><div className="mobile-detail-grid"><div className="col-span-2"><span>Ação</span><b>{c.action_type||'-'}</b></div><div><span>Fase</span><b>{c.phase||'-'}</b></div><div><span>Responsável</span><b>{c.responsible||'-'}</b></div><div><span>Comarca</span><b>{c.district||'-'}</b></div><div><span>Valor</span><b>{money(c.claim_value)}</b></div>{c.opposing_party&&<div className="col-span-2"><span>Parte contrária</span><b>{c.opposing_party}</b></div>}</div></div></details>)}</div>
    <ServerTablePagination basePath="/app/processos" page={page} pageSize={pageSize} totalItems={totalRows}/>{!rows.length&&<p className="empty-state">Nenhum processo cadastrado.</p>}</div>;
}
